### ISSUE TITLE
About Filtering Data

### ISSUE THREAD

**Issue by darkrpd** [ketanjawahire/FacebookClient#25]
Hello,

First of all many thanks for awesome project like that. 

How can I filter my request? For example filter my data according to time_created column between two dates.

Should I use AddQueryParameter method or anything else ? Could you give a simple example ?

Thanks for advance

**Comment by ketanjawahire** [comment]
Hi @darkrpd 
I assume you must have figured out the solution already. Still, I will try to answer it.
This SDK basically tries to create API request for you based in the input parameter provided. 
If API call supports filtering by passing any parameter through query string then you should use AddQueryParmeter to add that as a request parameter. Same will be passed on to the API call.
