### ISSUE TITLE
v6 API support

### ISSUE THREAD

**Issue by jaluka** [ketanjawahire/FacebookClient#26]
Are you going to update to v6 as I get the following error when running your sample

Facebook.ApiClient.Exceptions.FacebookOAuthException: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v6.0.

**Comment by ketanjawahire** [comment]
Hi @jaluka,

I have already removed the check for validating API version from SDK. You have to pass the desired API version as input to the ApiClient instance. 

Can you post some code snippet that you are trying? It will help me understand the issue better.
